### PR TITLE
updated dynamic simulation functions with test case

### PR DESCRIPTION
**Pull request by joyxyz1994**
Hey @yoelcortes, @yalinli2 and I've updated the functions related to dynamic simulations and added a module for tracking time-series data during simulation. A simple test system involving `DynamicInfluent`, `Splitter`, and `Mixer` was added to `test_qsdsan.py`. They are all `qsdsan.SanUnit` objects. `MixTank` wasn't explicitly tested here, because the algorithm would be like a non-reactive CSTR. I will compile a list of functions and attributes necessary for a `Unit` or a `Stream` to be able to simulated dynamically. In the meantime, please review the updates and let me know if anything needs to be changed. Thanks!

### CODE REVIEW

**Comment by yalinli2** [comment]
Thanks @joyxyz1994 !
Yoel, this PR will also fix the previous failed EXPOsan tests, you'll notice that I updated GitHub workflow (dfa5644b1c184ac69b52c4fe9429dddaa93f5b7d) that it'll install the QSDsan/EXPOsan on GitHub (otherwise the tests won't pass)

Additionally, I added a try/except block in `reset_cache` (0ae4f845e96e850010fd45eb5e6a976cec1747f5) as not all units' `reset_cache` take arguments, feel free to update as you see fit, thanks!

**Comment by yoelcortes** [comment]
Perfect, I'll have a detailed look at it on Friday :)

**Comment by yalinli2** [comment]
FYI, the recent builds (after I merged in `master`) failed because I haven't pushed the updated QSDsan to the `main` branch, my `beta` branch's builds passed:
https://github.com/QSD-Group/QSDsan/actions/runs/1900010533

**Comment by yalinli2** [comment]
OK tests relevant to QSDsan passed, but they ultimately failed due to other parts

**Comment by yoelcortes** [comment]
Thanks so much, everyone for working on this! I made a small pull request to QSDsan to fix a bug associated with old property_array behavior. Everything looks awesome!

**Comment by yalinli2** [comment]
Wonderful!

**Pull request merged**
