### PR TITLE
Unit group improvements

### PR DESCRIPTION
**Pull request by sarangbhagwat**
See issue ['Unit group metric fractions do not add to 100%'](https://github.com/BioSTEAMDevelopmentGroup/biosteam/issues/146).

This adds an argument 'scale_to_positive_values', set to True by default to retain original behavior.

**Before:**
```
df_TEA_breakdown = bst.UnitGroup.df_from_groups(
    unit_groups, fraction=True,
)

print(df_TEA_breakdown)
```
Output:
     Net electricity production
0                           100
100                       -2.92
200                       -3.55
300                      -0.808

**After:**
```
df_TEA_breakdown = bst.UnitGroup.df_from_groups(
    unit_groups, fraction=True,
    scale_fractions_to_positive_values=False
)

print(df_TEA_breakdown)
```
Output:
     Net electricity production
0                           108
100                       -3.14
200                       -3.83
300                      -0.872

### CODE REVIEW

**Comment by yoelcortes** [comment]
@sarangbhagwat, this is a nice addition and thanks for the typo correction. Could you add a test (either in the docstring or as a test function in the tests folder) and make sure all tests are passing? I'll get it merged as soon as this gets done.

**Comment by sarangbhagwat** [comment]
Sure thing! I just added both.

**Comment by yoelcortes** [comment]
Nice, I think it is almost ready. Here is what is left:
* Use `...` instead of `>>>` when making multiple lines (just line in the ipython console).
* Let's avoid `print` for consistency in BioSTEAM and most libraries out there. For example, use `df_TEA_breakdown` instead of `print(df_TEA_breakdown)` is sufficient.
* Remove empty lines in examples. Those are only necessary if there is a note between commands.

The first point is what is breaking the tests. Before committing, you check if tests are passing locally with:

```pytest . -v --disable-numba=1```



Thanks!

**Comment by sarangbhagwat** [comment]
Fixed the docstring (and the one for UnitGroup, which was failing due to the "Materiral" typo that was fixed in my earlier commit). Thanks!

**Comment by yoelcortes** [comment]
@sarangbhagwat, great! No worries on the error in the tests. It has to do with IDs not matching. I'll take care of it soon and merge.

Thanks again!

**Comment by yoelcortes** [comment]
@sarangbhagwat, I accidentally included changes that relies on thermosteam's `show` branch which is currently under review. All tests should be passing. I'll wait until that gets merged before merging this branch.

**Review by yoelcortes — APPROVED** [review]
All looks good: 
- [x] Clear contribution
- [x] Documentation
- [x] Tests
- [x] Code coverage

Thanks!

**Pull request merged**
