### PR TITLE
Extend system tutorial notebook

### PR DESCRIPTION
**Pull request by BenPortner**
First shot at including the points mentioned in https://github.com/BioSTEAMDevelopmentGroup/biosteam/pull/121 in the tutorial:
- add section about two-step convergence
- add section about tolerances

### CODE REVIEW

**Comment by BenPortner** [comment]
It seems that the CI fails with both COOLPROP and DADGOSTAR_SHAW methods. Not sure why because it runs fine locally. Can you try on your PC @yoelcortes?

**Comment by yoelcortes** [comment]
@BenPortner, Thanks for giving this a shot! Just a few quick notes:

* The solver always starts from previous results regardless of `skip_setup`. The only time previous results are not used is when streams are explicitly emptied. All the `System._setup` does is run `<Unit>_setup()` and reconnect streams in case multiple configurations are being handled by the same unit operations. 
* Skip setup can lead to errors in unit operation results because design and cost dictionaries are not cleaned (as they would be with the setup). This can happen if compressor types are set to default and the pressure varies in a stream (this is one example of many). I won't be including skip setup in the tutorial. Instead, I'll include an example with `N_runs` where a specification changes unit operations upstream.

If you ever need to try to converge multiple times, the following would be much faster than running simulate multiple times with skip_setup:

```python
# This is would work in your case, where streams are not being reconnected during system simulation.
# I won't be including this in the tutorial either.
system._setup()
system.converge() 
system.converge() # Converge as many times as you need
system._summary() # Run design and costing
```

I am not too sure if leaving skip_setup in the code is a good idea, but I won't remove it if you have any code that depends on it.

Thanks!

**Comment by BenPortner** [comment]
Hello @yoelcortes,

> The only time previous results are not used is when streams are explicitly emptied. 

Which is what happens in `HXProcess._setup()` in the example.

> I won't be including skip setup in the tutorial. Instead, I'll include an example with N_runs where a specification changes unit operations upstream.

Not sure what is meant here. I think the tutorial should show how to make the nitrogen liquefaction example converge.

> Skip setup can lead to errors in unit operation results because design and cost dictionaries are not cleaned
Does calling `System.converge()` twice prevent these problems? If not, we need to find a solution. There should be a way to run systems with a HXProcess twice without resetting everything or causing other problems.

**Comment by yoelcortes** [comment]
@BenPortner 

Yes, I plan on leaving the nitrogen liquefaction example in. I like the system examples you've proposed.

Regarding streams being emptied in HXprocess, this is an old behavior I had forgotten about. Thanks for noting this! It prevented an old bug when a recycle loop changed drastically between simulations. I think this behavior is not consistent with BioSTEAM, I went ahead made it so that the user will need to explicitly ask for it. 

Yes, `System.converge` prevents these problems because the `_design` and `_cost` methods are not run in `converge`. But the 4-lines of code I wrote earlier is not that pretty. I updated the `<System>.N_runs` attribute to allow a system instance to converge multiple times (not just run a single loop multiple times) when a recycle loop is present. In other words:

```python
# These two lines are equivalent to the 
# commented lines below.
system.N_runs = 2
system.simulate()

# system._setup()
# if system.recycle:
#     for i in range(system.N_runs): system.converge() 
# else:
#     for i in range(system.N_runs): system._run() 
# system._summary()

# Before my recent commit, this was the old behavior:
# system._setup()
# for i in range(system.N_runs): system._run() 
# system._summary()

```
I'll start working on getting this tutorial in BioSTEAM over the weekend. I will also make sure the nitrogen liquefaction example can converge in a single simulation. 

Thanks!

**Comment by yoelcortes** [comment]
@BenPortner, I added T and P to the accelerated iteration solver (before only flow rates were passed to the solver). This stabilized convergence with oscillating temperatures. Now the following works without having to change heat capacity methods:

```python
import biosteam as bst

# setup thermodynamic backend
N2 = bst.Chemical('N2')
bst.settings.set_thermo([N2])
N2.Cn.g.method = "COOLPROP"
N2.Cn.l.method = "COOLPROP"
N2.reset_free_energies()
bst.settings.mixture.include_excess_energies = True

# inlet
inlet = bst.Stream("inlet", N2=2.75, units="kg/s", T=6.85+273.15, P=200e5, phase="g")

# recycle HX
regenerator = bst.units.HXprocess("regenerator", ins=(inlet, "flash_gas"), outs=("throttle_in", 'out'), dT=9.55)
throttle_in = regenerator.outs[0]

# throttling
valve = bst.units.IsenthalpicValve("expansion", ins=throttle_in, outs="valve_out", P=1e5, vle=True)
valve_out = valve.outs[0]

# flash drum
flash = bst.units.Flash("flash", ins=valve_out, outs=("flash_gas", "flash_liquid"), Q=0, P=1e5)
gas_out = flash.outs[0]
liquid_out = flash.outs[1]

# connect flash gas to regenerator
regenerator.ins[1] = gas_out

# run simulation
sys = bst.main_flowsheet.create_system('flowsheet_sys')
sys.simulate()
regenerator.outs[0].show()
"""
Stream: throttle_in from <HXprocess: regenerator> to <IsenthalpicValve: expansion>
 phase: 'l', T: 126.2 K, P: 2e+07 Pa
 flow (kmol/hr): N2  353
"""
```

**Comment by yoelcortes** [comment]
@BenPortner, just wanted to let you know that I'm planning on completing the tutorial within a couple of days. I'll also get tests passing too. I just completed some updates to biorefinery models, so I can finally work on updating tests.

**Comment by yoelcortes** [comment]
@BenPortner, thanks for the help on this. I went ahead and merged. If there is anything else you'd like to add, please do and I can merge again.

Thanks!

**Pull request merged**
