### PR TITLE
HTML system diagrams

### PR DESCRIPTION
**Pull request by BenPortner**
This PR adds an `html` output format for system diagrams. The format is equivalent to `svg` except it adds informative tooltips:
Recording 2022-08-29 at 16 13 50

# Open issues:
- [x] use CDN versions of `digraph.js` and `digraph.css` to make them work independent of output file location
- [x] add tooltips for other unit types (currently only compressors)
- [x] find out why tippy.js adds white space to node tooltips
- [x] add tooltips only if output format is html (~Yoel edit: or svg?~)
- [ ] make sure it works for `save_digraph` and `display_digraph`
- [ ] add essential unit parameters (e.g. efficiency) to tooltip
- [x] make stream tooltips a nice pandas series (or 1 column dataframe).

# Help needed
@yoelcortes: Do you know a clever way to include other unit types without manually modifying each `_graphics.tailor_xyz_node` function? Perhaps we can make these part of the class definitions and have `_unit.Unit` provide a default tooltip function?

### CODE REVIEW

**Comment by yoelcortes** [comment]
@BenPortner, this is awesome. It is also great to see you added it for streams too. A good way to make this work for all units is to add it in the `Unit.get_node` method. 

Regarding adding tooltips only if format is html, we can have a new `biosteam.preferences.diagram_format` attribute that defaults to 'html'. Then in `System.diagram`, have something like this:

```python 
        preferences = bst.preferences
        with preferences.temporary(): # This makes any changes to preferences temporary
            if number is not None: preferences.number_path = number
            if label is not None: preferences.label_streams = label
            if profile is not None: preferences.profile = profile
            if format is not None: preferences.diagram_format = format # Override if not given
            if kind == 0 or kind == 'cluster':
                f = self._cluster_digraph(graph_attrs)
            elif kind == 1 or kind == 'thorough':
                f = self._thorough_digraph(graph_attrs)
            elif kind == 2 or kind == 'surface':
                f = self._surface_digraph(graph_attrs)
            elif kind == 3 or kind == 'minimal':
                f = self._minimal_digraph(graph_attrs)
            else:
                raise ValueError("kind must be one of the following: "
                                 "0 or 'cluster', 1 or 'thorough', 2 or 'surface', "
                                 "3 or 'minimal'")
            if display or file:
                finalize_digraph(f, file) # Format will not be passed to finalize_diagram anymore
            else:
                return f
```

I have a question regarding output format and tooltips. In `System.diagram`, we have the following code:
```python
if format == 'html': graph_attrs['format'] = 'svg' # because html will cause error
```
Is this temporary? I thought the format would need to be 'html' to inject js in `finalize_digraph` 

Thanks!

**Comment by yoelcortes** [comment]
@BenPortner, that makes sense, we can keep the format as an input parameter to `format_digraph` and still have the default in preferences. Note that the graphviz digraph is created outside `format_digraph`, so (although it is not ideal) the functions that create the nodes and edges will be using the values listed in preferences to decide whether to add tooltips (among other things like the color/style/numbering).

Yes, let's remove the format from `graph_attrs`, it seems like it is not needed since we set the final format anyway.

Thanks a bunch!

**Comment by BenPortner** [comment]
@yoelcortes: It would be nice to include essential initialization parameters in the tooltips (e.g. efficiency of a turbine, number of stages for a multicompressor). Do you know a clever way to include these while preventing duplication of the `result()` data?

**Comment by yoelcortes** [comment]
@BenPortner, yes! I meant to mention this to you earlier but forgo. Thanks for asking! We can extend the result() dataframe using the `_get_design_info() -> Sequence[tuple[name, value, units]]` method. This method will add rows in the `results()` dataframe as if they were additional items in the design_results dictionary. For example:

```python
def _get_design_info(self):
      return [
      ('Residence time', self.tau, 'hr'),
      ('Conversion efficiency', self.efficiency, ''),
      ('Working volume fraction', 0.8, '')
] 
```

Hope this help!

**Comment by BenPortner** [comment]
Hi @yoelcortes,

Thanks for your help with this! I'm a little bit swamped right now, so I cannot pour as much time into it as I'd like.

Just a quick question: Did you tick the "make sure it works for save_digraph and display_digraph" box? Last time I tried, the HTML output did not work in notebooks because of [this bug](https://github.com/atomiks/tippyjs/issues/1077), which I am waiting to be resolved.

Ben

**Comment by yoelcortes** [comment]
@BenPortner, thanks for the notes on this! The html output doesn't show tooltips in jupyter notebooks (yet) unfortunately, but it is still working for me. 

Your right about the svg formating, I just tried it jaja. I'll make tooltips only available for html format.

I think I'll set the default format back to svg since html is still not working on jupyter notebooks

Thanks!

**Review by yoelcortes — APPROVED** [review]
I'm super stoked about these new features. Thanks, @BenPortner! We still got a couple of items left to add, but I'll go ahead and merge to not have branches diverge too much.

**Comment by yoelcortes** [comment]
I was able to get html diagrams to show on jupyter notebooks, but it requires to save the file:
https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/8f66a0b8aa7a82954cb24bcac562f18067d98e69/biosteam/digraph/digraph.py#L525

I wasn't able to get the file to save in a path other than directly in the same folder (everything else I tried failed...). It would me nice if they could be saved as part of jupyter notebook ipynb checkpoints... or something of the sort.

**Comment by BenPortner** [comment]
Hi @yoelcortes,

Just to clarify: You don't see the HTML diagrams in the notebook if you don't save it? That is unusual, because last time I tried, it worked for me. The only thing that didn't work were the tooltips.

Which error do you get when saving in another folder?

**Pull request merged**
