### PR TITLE
Add `IsentropicTurbine` model

### PR DESCRIPTION
**Pull request by BenPortner**
Adds a model for isentropic expansion of gases in a turbine.
Includes tests but no cost model.

### CODE REVIEW

**Comment by yalinli2** [comment]
Just an idea, would it be better to mark a PR as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) if it's not ready for reviewing?

**Comment by BenPortner** [comment]
@yoelcortes In my opinion, the PR is ready for review. I don't plan to add anything else.

**Comment by yoelcortes** [comment]
OK! I'll try to get to it over the weekend. Thanks!

**Comment by yoelcortes** [comment]
@BenPortner, just had a look at this and overall it looks good. Thanks so much for the thought you put in the graphviz diagrams. I understand there are limitations to the software (which I also faced) and we may need to work around it a bit. I have planed the following changes/enhancements:

1. Implement Warren's turbine design/costing algorithm which has some overlap with the compressor algorithm. The code on driver selection will be removed to only use electric motor (in reverse) so the boilerplate code will be reduced a bit (e.g., no design factors). I'll take care of this sometime next weekend.
2. Add a warning (similar to valves) that the turbine will be ignored if the inlet pressure is lower than the outlet specification (and ignore design and costing when this happens). Feel free to add this, but I got it if not. We should probably do something similar for compressors eventually. 
3. Add a valve image for both dark ('#555f69') and light (unit_color='white:#CDCDCD', unit_periphery_color='#4e4e4e') mode. **Could you take care of this?**
4. Choose the valve image depending on whether `preference.unit_color` is in light or dark mode. As a fallback, default to dark mode (if `preferences.unit_color` is other than the defaults for each mode).  I'd be happy to do so later, but it would be nice if you could add it.

It is exciting for me to see these contributions. I love the detail with turbine/compressor/valve shapes. I plan on getting this pull request merged before working on the new tutorial chapter on solver tolerances and available methods. 

Thanks!

**Comment by yoelcortes** [comment]
Great work, @BenPortner! The tests failed because of a mismatch with the number of heat utilities (now it is 1 in case a steam turbine is used as the driver). Regarding graphviz diagrams, I just had to move your code inside the `tailor_unit_diagram` function.

The "valve_dark.png" file appears to have a white background. Could you update this with a transparent background? The "valve_light.png" is good. As soon as this is updated, I'll go ahead and merge.

Thanks!

**Comment by yoelcortes** [comment]
@BenPortner, I have one more request for `valve_light.png`, could you make the edge slightly thicker?

image

image

**Comment by BenPortner** [comment]
@yoelcortes 
- [x] adapted the valve_light periphery color
- [ ] The CI doesn't fail due to tolerances or numba. It fails because it doesn't use the newest version of thermosteam. Fixing [the zip bug]( https://github.com/BioSTEAMDevelopmentGroup/thermosteam/commit/a12bdefd400550a56bd368cce3327ca46c52dab3) changed the results significantly

**Review by yoelcortes — APPROVED** [review]
Great contributions! All is ready for merging ^_^

**Comment by yoelcortes** [comment]
Ahh, I see. In that case it is OK. The CI can be fixed later. Thanks again!

**Pull request merged**
