### PR TITLE
Enable skipping non-Facility units that have zero flow in

### PR DESCRIPTION
**Pull request by sarangbhagwat**
This pull adds a parameter "skip_non_facility_units_with_zero_flow" to biosteam.settings. If True, this will skip a unit's simulate, run, and _summary calls IFF (i) that unit is not a facility AND (ii) that unit has F_mol_in = 0. A doctest is also added (this can be moved to a better place if needed). 

This pull (unfortunately) also includes a commit (https://github.com/BioSTEAMDevelopmentGroup/biosteam/pull/155/commits/c98c5293ee0b196ca104fb12845ab763e8f2502c) for a separate, very minor pull (https://github.com/BioSTEAMDevelopmentGroup/biosteam/pull/154) that can be reviewed in this PR instead. Once reviewed, I can delete the other PR.

### CODE REVIEW

**Comment by yoelcortes** [comment]
@sarangbhagwat, nice, I'll try to review sometime tomorrow. In the meantime, could you also add tests to confirm the new feature works as described?

Thanks,

**Comment by sarangbhagwat** [comment]
> @sarangbhagwat, nice, I'll try to review sometime tomorrow. In the meantime, could you also add tests to confirm the new feature works as described?
> 
> Thanks,

Thanks, @yoelcortes. No rush. I've already added a doctest to Unit._should_run -- this can be moved to a better place if needed. Did you mean any tests besides what's covered there?

**Comment by yoelcortes** [comment]
@sarangbhagwat,

Let's remove the doctest and use test functions instead (in test_unit.py). We can add the documentation to the property in the settings object and leave out the doctest for now. We can avoid adding the documentation to private members (those with a leading underscore "_") since they do not appear in the documentation. 

It would also be great if we can simplify what we test for. We can use a simpler unit like a mixing tank. I think we mostly just need to check the following:

* All outlets are empty if feed is empty (e.g., `assert all([i.isempty() for i in unit.outs])`). You may notice that your doctest shows that outlet streams are not empty when the unit is "skipped".
* No capital or utility costs (e.g., `assert unit.installed_cost == 0` and `assert unit.installed_cost == 0` )

This is just an idea, but it may be worth adding a specification to assert that the unit did not run when the skip-flag is on:
```python
# when flag is on
bst.settings.empty_unit_skip_flag = True # Excuse my pseudo code
@unit.add_specification
def f(): raise RuntimeError('unit simulated')
feed.empty()
unit.simulate() # No error
bst.settings.empty_unit_skip_flag = False
with pytest.raises(RuntimeError)
    unit.simulate() # This will error

```

I can update the code and minor details on Tuesday, once we can get these test functions down.
Thanks!

**Comment by sarangbhagwat** [comment]
Thanks @yoelcortes, we can move tests to test_unit and change it to test a MixTank object. 

If we're testing for empty outlets, however, we need to implement emptying outlets in Unit.run, as streams will be cached from a previous simulation of that unit if either (a) the unit's feed was previously not empty or (b) the flag was previously set to False. Do you mean we should empty outlets in Unit.run?

Thanks!

**Comment by yoelcortes** [comment]
@sarangbhagwat, yeah, emptying outlets in Unit.run should work well.

Thanks!

**Comment by sarangbhagwat** [comment]
@yoelcortes I have added tests using a MixTank object. I've also ensured installed_cost and utility_cost are zero by using Unit.empty (also updated this to change _utility_cost to zero, which it wasn't covering before). I think you were saying we should simply test with and without the flag on, but I've additionally tested for with and without empty streams -- I think this is necessary, but happy to discuss. Feel free to suggest other changes.

Thanks!

**Comment by yoelcortes** [comment]
@sarangbhagwat, awesome! I took a quick look and all looks good. I'll go through it in more detail tomorrow. I plan on making minor changes to names and documentation and hopefully merge (unless there are any issues to resolve). 

Thanks!

**Review by yoelcortes — APPROVED** [review]
@sarangbhagwat, great work! 

- [x] Relevant contribution.
- [x] Documentation (it's clear).
- [x] Tests (all is tested). 
- [x] Code coverage (everything is checked).

I made some minor edits, including:
* Moved skip-flag variable to Unit (so its now a class attribute and wont affect facilities). This also allows us to change the flag for individual units if we really need to. 
* Renames (simply for my preference and consistency with general language previously used). The skip flag is now called `biosteam.settings.skip_simulation_of_units_with_empty_inlets`.
* Docstring changes to not make it too technical (for users not familiar with biosteam internals).

Thanks!

**Pull request merged**
